@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(gateway, "Api Gateway", "Node Js")


System_Boundary(serviceBoundary, "Device Service") {
    Container(manageDeviceController, "Manage Device Controller", "Управление существующим устройством")
    Container(connectDeviceController, "Connect Device Controller", "Подключение/Отключение устройства пользователем")
    Container(newDeviceController, "New Device Controller", "Добавление интеграции с устройством админом")


    Container(runCommandComponent, "Run Command Component", "Запуск для устройства по протоколу")
    Container(defineDeviceComponent, "Define Device Component", "Определеить устройство и возможные команды")
}
    Container_Ext(adapterDevice, "Device Adapter", "Работает с коммандами девайса")
    Container_Ext(db, "DeviceDB", "Хранит информацию о девайсах")


Rel(gateway, manageDeviceController, "HTTP")
Rel(gateway, connectDeviceController, "HTTP")
Rel(manageDeviceController, defineDeviceComponent, "Uses")
Rel(connectDeviceController, defineDeviceComponent, "Uses")
Rel(defineDeviceComponent, runCommandComponent, "Uses")
Rel(defineDeviceComponent, db, "Read")
Rel(runCommandComponent, adapterDevice, "HTTP/Zigbee/MQTT")
Rel(gateway, newDeviceController, "HTTP")
Rel(newDeviceController, db, "Write")



@enduml