@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(gateway, "Api Gateway", "Node Js")

System_Boundary(serviceBoundary, "User Service") {
    Container(userDataController, "User Controller", "Управление юзером")
    Container(authController, "Auth Controller", "Аутентификация")
    Container(userComponent, "User Component", "Функциональность управления юзером")
    Container(securityComponent, "Security Component", "Функциональность смены пароля и авторизации")
}
    Container_Ext(userDB, "UserDB", "Хранит информацию о пользователях")


Rel(gateway, authController, "HTTP")
Rel(gateway, userDataController, "HTTP")
Rel(authController, securityComponent, "Uses")
Rel(userComponent, userDB, "Uses")
Rel(userDataController, userComponent, "Uses")

Rel(securityComponent, userDB, "Uses")


@enduml